VidyaCat.MVC/Controllers/DeveloperController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidyaCat.Data;
using VidyaCat.Models.DeveloperModels;
using VidyaCat.Services;

namespace VidyaCat.MVC.Controllers
{
    public class DeveloperController : Controller
    {
        // GET: Developer
        public ActionResult Index()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new DeveloperService(userID);
            var model = svc.GetDevelopers();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DeveloperCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var svc = CreateDeveloperService();
            if (svc.CreateDeveloper(model))
            {
                TempData["SaveResult"] = "Developer was successfully added to the database!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "An error occurred while attempting to add the developer to the database - changes not saved.");
            return View(model);
        }

        // GET: Details
        public ActionResult Details(int id)
        {
            var svc = CreateDeveloperService();
            var model = svc.GetDeveloperByID(id);
            return View(model);
        }

        // GET: Developers by Region
        public ActionResult IndexByRegion(Region region)
        {
            var svc = CreateDeveloperService();
            var model = svc.GetDevelopersByRegion(region);
            return View(model);
        }

        // GET: Developers by Status   
        public ActionResult IndexByStatus(bool status)
        {
            var svc = CreateDeveloperService();
            var model = svc.GetDevelopersByStatus(status);
            return View(model);
        }

        // GET: Developers by Type
        public ActionResult IndexByType(bool type)
        {
            var svc = CreateDeveloperService();
            var model = svc.GetDevelopersByType(type);
            return View(model);
        }

        // GET: Edit
        public ActionResult Edit(int id)
        {
            var svc = CreateDeveloperService();
            var details = svc.GetDeveloperByID(id);
            var model = new DeveloperEdit
            {
                DeveloperID = details.DeveloperID,
                DeveloperName = details.DeveloperName,
                Region = details.Region,
                IsMajor = details.IsMajor,
                IsActive = details.IsActive
            };

            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, DeveloperEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.DeveloperID != id)
            {
                ModelState.AddModelError("", "ID mismatch");
                return View(model);
            }

            var svc = CreateDeveloperService();
            if (svc.UpdateDeveloper(model))
            {
                TempData["SaveResult"] = "Developer info successfully updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "An error occurred while attempting to edit the developer info - changes not saved.");
            return View(model);
        }

        // GET: Delete
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateDeveloperService();
            var model = svc.GetDeveloperByID(id);
            return View(model);
        }

        // POST: Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDeveloper(int id)
        {
            var svc = CreateDeveloperService();
            svc.DeleteDeveloper(id);
            TempData["SaveResult"] = "Developer successfully deleted from the database.";
            return RedirectToAction("Index");
        }

        private DeveloperService CreateDeveloperService()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new DeveloperService(userID);
            return svc;
        }
    }
}

VidyaCat.MVC/Controllers/GameController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidyaCat.Data;
using VidyaCat.Models.GameModels;
using VidyaCat.Services;

namespace VidyaCat.MVC.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new GameService(userID);
            var model = svc.GetGames();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GameCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var svc = CreateGameService();
            if (svc.CreateGame(model))
            {
                TempData["SaveResult"] = "Game successfully added to database.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "An error occurred while attempting to add the game to the database - changes not saved.");
            return View(model);
        }

        // GET: Details
        public ActionResult Details(int id)
        {
            var svc = CreateGameService();
            var model = svc.GetGameByID(id);
            return View(model);
        }

        // GET: Games by Developer
        public ActionResult IndexByDeveloper(string devName)
        {
            var svc = CreateGameService();
            var model = svc.GetGamesByDeveloper(devName);
            return View(model);
        }

        // GET: Games by Platform
        public ActionResult IndexByPlatform(string platName)
        {
            var svc = CreateGameService();
            var model = svc.GetGamesByPlatform(platName);
            return View(model);
        }

        // GET: Games By Year
        public ActionResult IndexByReleaseYear(int releaseYear)
        {
            var svc = CreateGameService();
            var model = svc.GetGamesByYear(releaseYear);
            return View(model);
        }

        // GET: Games by Genre
        public ActionResult IndexByGenre(Genre genre)
        {
            var svc = CreateGameService();
            var model = svc.GetGamesByGenre(genre);
            return View(model);
        }

        // GET: Games by Rating
        public ActionResult IndexByRating(Rating rating)
        {
            var svc = CreateGameService();
            var model = svc.GetGamesByRating(rating);
            return View(model);
        }

        // GET: Edit
        public ActionResult Edit(int id)
        {
            var svc = CreateGameService();
            var detail = svc.GetGameByID(id);
            var model = new GameEdit
            {
                GameID = detail.GameID,
                Title = detail.Title,
                ReleaseDate = detail.ReleaseDate,
                Genre = detail.Genre,
                FirstSubgenre = detail.FirstSubgenre,
                SecondSubgenre = detail.SecondSubgenre,
                ThirdSubgenre = detail.ThirdSubgenre,
                PlatformNames = detail.PlatformNames,
                DeveloperName = detail.DeveloperName
            };

            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, GameEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.GameID != id)
            {
                ModelState.AddModelError("", "ID mismatch");
                return View(model);
            }

            var svc = CreateGameService();
            if (svc.UpdateGame(model))
            {
                TempData["SaveResult"] = "The game info was succesfully updated!";
                return View(model);
            }

            ModelState.AddModelError("", "An error occurred while attempting to edit game info - changes not saved.");
            return View(model);
        }

        // GET: Delete
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateGameService();
            var model = svc.GetGameByID(id);
            return View(model);
        }

        // POST: Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteGame(int id)
        {
            var svc = CreateGameService();
            svc.DeleteGame(id);
            TempData["SaveResult"] = "Game successfully deleted from database.";
            return RedirectToAction("Index");
        }

        private GameService CreateGameService()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new GameService(userID);
            return svc;
        }
    }
}

VidyaCat.MVC/Views/Developer/Create.cshtml
@model VidyaCat.Models.DeveloperModels.DeveloperCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Developer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DeveloperName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeveloperName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeveloperName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMajor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMajor)
                    @Html.ValidationMessageFor(model => model.IsMajor, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VidyaCat.MVC/Views/Developer/Delete.cshtml
@model VidyaCat.Models.DeveloperModels.DeveloperDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Developer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeveloperName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VidyaCat.MVC/Views/Developer/Details.cshtml
@model VidyaCat.Models.DeveloperModels.DeveloperDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Developer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeveloperName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegionName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GamesDeveloped)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GamesDeveloped)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.DeveloperID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VidyaCat.MVC/Views/Developer/Edit.cshtml
@model VidyaCat.Models.DeveloperModels.DeveloperEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Developer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeveloperID)

        <div class="form-group">
            @Html.LabelFor(model => model.DeveloperName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeveloperName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeveloperName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Region, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMajor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMajor)
                    @Html.ValidationMessageFor(model => model.IsMajor, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VidyaCat.MVC/Views/Developer/Index.cshtml
@model IEnumerable<VidyaCat.Models.DeveloperModels.DeveloperListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink($"{item.DeveloperName}", "IndexByDeveloper", "Game", new { id = item.DeveloperID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Region}", "IndexByRegion", "Developer", new { region = item.Region }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Type}", "IndexByType", "Developer", new { type = item.Type }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Status}", "IndexByStatus", "Developer", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DeveloperID }) |
            @Html.ActionLink("Details", "Details", new { id=item.DeveloperID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DeveloperID })
        </td>
    </tr>
}

</table>

VidyaCat.MVC/Views/Developer/IndexByRegion.cshtml
@model IEnumerable<VidyaCat.Models.DeveloperModels.DeveloperListItem>

@{
    ViewBag.Title = "IndexByRegion";
}

<h2>IndexByRegion</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink($"{item.DeveloperName}", "Details", "Developer", new { id = item.DeveloperID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Region)
        </td>
        <td>
            @Html.ActionLink($"{item.Type}", "IndexByType", "Developer", new { type = item.Type }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Status}", "IndexByStatus", "Developer", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.DeveloperID }) |
            @Html.ActionLink("Details", "Details", new { id=item.DeveloperID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.DeveloperID })
        </td>
    </tr>
}

</table>

VidyaCat.MVC/Views/Developer/IndexByStatus.cshtml
@model IEnumerable<VidyaCat.Models.DeveloperModels.DeveloperListItem>

@{
    ViewBag.Title = "IndexByStatus";
}

<h2>IndexByStatus</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink($"{item.DeveloperName}", "Details", "Developer", new { id = item.DeveloperID }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.ActionLink($"{item.Region}", "IndexByRegion", "Developer", new { region = item.Region }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.ActionLink($"{item.Type}", "IndexByType", "Developer", new { type = item.Type }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DeveloperID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DeveloperID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DeveloperID })
            </td>
        </tr>
    }

</table>

VidyaCat.MVC/Views/Developer/IndexByType.cshtml
@model IEnumerable<VidyaCat.Models.DeveloperModels.DeveloperListItem>

@{
    ViewBag.Title = "IndexByType";
}

<h2>IndexByType</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Region)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink($"{item.DeveloperName}", "Details", "Developer", new { id = item.DeveloperID }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.ActionLink($"{item.Region}", "IndexByRegion", "Developer", new { region = item.Region }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.ActionLink($"{item.Status}", "IndexByStatus", "Developer", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.DeveloperID }) |
                @Html.ActionLink("Details", "Details", new { id = item.DeveloperID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.DeveloperID })
            </td>
        </tr>
    }

</table>