VidyaCat.MVC/Controllers/PlatformController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VidyaCat.Services;
using VidyaCat.Data;
using VidyaCat.Models.PlatformModels;

namespace VidyaCat.MVC.Controllers
{
    public class PlatformController : Controller
    {
        // GET: Platform
        public ActionResult Index()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new PlatformService(userID);
            var model = svc.GetPlatforms();
            return View(model);
        }

        // GET: Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlatformCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var svc = CreatePlatformService();

            if (svc.CreatePlatform(model))
            {
                TempData["SaveResult"] = "Platform was successfully added to database!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "An error occurred while attempting to add the platform to the database - changes not saved.");
            return View(model);
        }

        // GET: Details
        public ActionResult Details(int id)
        {
            var svc = CreatePlatformService();
            var model = svc.GetPlatformByID(id);
            return View(model);
        }

        // GET: Platforms by Year
        public ActionResult IndexByYear(int releaseYear)
        {
            var svc = CreatePlatformService();
            var model = svc.GetPlatformsByYear(releaseYear);
            return View(model);
        }

        // GET: Platforms by Brand
        public ActionResult IndexByBrand(Brand brand)
        {
            var svc = CreatePlatformService();
            var model = svc.GetPlatformsByBrand(brand);
            return View(model);
        }

        // GET: Platforms by Status
        public ActionResult IndexByStatus(string status)
        {
            var svc = CreatePlatformService();
            var model = svc.GetPlatformsByStatus(status);
            return View(model);
        }

        // GET: Edit
        public ActionResult Edit(int id)
        {
            var svc = CreatePlatformService();
            var details = svc.GetPlatformByID(id);
            var model = new PlatformEdit
            {
                PlatformID = details.PlatformID,
                Brand = details.Brand,
                PlatformName = details.PlatformName,
                ReleaseDate = details.ReleaseDate
            };
            return View(model);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PlatformEdit model)
        {
            if (!ModelState.IsValid) return View(model);
            
            if (model.PlatformID != id)
            {
                ModelState.AddModelError("", "ID mismatch");
                return View(model);
            }

            var svc = CreatePlatformService();
            if (svc.UpdatePlatform(model))
            {
                TempData["SaveResult"] = "Platform info was successfully updated!";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "An error occurred while attempting to update the platform info - changes not saved.");
            return View(model);
        }

        // GET: Delete
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePlatformService();
            var model = svc.GetPlatformByID(id);
            return View(model);
        }

        // POST: Delete
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePlatform(int id)
        {
            var svc = CreatePlatformService();
            svc.DeletePlatform(id);
            TempData["SaveResult"] = "Platform was successfully deleted!";
            return RedirectToAction("Index");
        }

        private PlatformService CreatePlatformService()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var svc = new PlatformService(userID);
            return svc;
        }
    }
}

VidyaCat.MVC/Views/Platform/Create.cshtml
@model VidyaCat.Models.PlatformModels.PlatformCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Platform</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Brand, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlatformName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlatformName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlatformName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCurrent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCurrent)
                    @Html.ValidationMessageFor(model => model.IsCurrent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VidyaCat.MVC/Views/Platform/Delete.cshtml
@model VidyaCat.Models.PlatformModels.PlatformDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Platform</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlatformName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlatformName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCurrent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCurrent)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VidyaCat.MVC/Views/Platform/Details.cshtml
@model VidyaCat.Models.PlatformModels.PlatformDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Platform</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlatformName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlatformName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsCurrent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsCurrent)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PlatformID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VidyaCat.MVC/Views/Platform/Edit.cshtml
@model VidyaCat.Models.PlatformModels.PlatformEdit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Platform</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PlatformID)

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Brand, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlatformName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlatformName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PlatformName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsCurrent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCurrent)
                    @Html.ValidationMessageFor(model => model.IsCurrent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VidyaCat.MVC/Views/Platform/Index.cshtml
@model IEnumerable<VidyaCat.Models.PlatformModels.PlatformListItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlatformName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink($"{item.Brand}", "IndexByBrand", "Platform", new { brand = item.Brand }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.PlatformName}", "Details", "Platform", new { id = item.PlatformID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.ReleaseDate.Date}", "IndexByYear", "Platform", new { releaseYear = item.ReleaseDate.Year }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Status}", "IndexByStatus", "Platform", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlatformID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlatformID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlatformID })
        </td>
    </tr>
}

</table>

VidyaCat.MVC/Views/Platform/IndexByBrand.cshtml
@model IEnumerable<VidyaCat.Models.PlatformModels.PlatformListItem>

@{
    ViewBag.Title = "IndexByBrand";
}

<h2>IndexByBrand</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlatformName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.ActionLink($"{item.PlatformName}", "Details", "Platform", new { id = item.PlatformID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.ReleaseDate.Date}", "IndexByYear", "Platform", new { releaseYear = item.ReleaseDate.Year }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.Status}", "IndexByStatus", "Platform", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlatformID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlatformID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlatformID })
        </td>
    </tr>
}

</table>

VidyaCat.MVC/Views/Platform/IndexByStatus.cshtml
@model IEnumerable<VidyaCat.Models.PlatformModels.PlatformListItem>

@{
    ViewBag.Title = "IndexByStatus";
}

<h2>IndexByStatus</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlatformName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink($"{item.Brand}", "IndexByBrand", "Platform", new { brand = item.Brand }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.PlatformName}", "Details", "Platform", new { id = item.PlatformID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.ReleaseDate.Date}", "IndexByYear", "Platform", new { releaseYear = item.ReleaseDate.Year }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlatformID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlatformID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlatformID })
        </td>
    </tr>
}

</table>

VidyaCat.MVC/Views/Platform/IndexByYear.cshtml
@model IEnumerable<VidyaCat.Models.PlatformModels.PlatformListItem>

@{
    ViewBag.Title = "IndexByYear";
}

<h2>IndexByYear</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlatformName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink($"{item.Brand}", "IndexByBrand", "Platform", new { brand = item.Brand }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink($"{item.PlatformName}", "Details", "Platform", new { id = item.PlatformID }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate.Date)
        </td>
        <td>
            @Html.ActionLink($"{item.Status}", "IndexByStatus", "Platform", new { status = item.Status }, htmlAttributes: new { @class = "indexLink" })
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PlatformID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PlatformID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PlatformID })
        </td>
    </tr>
}

</table>